### ISSUE TITLE
[Feature] chat embedded 

### ISSUE THREAD

**Issue by AdelEddarai** [DahnM20/ai-flow#5]
Add a feature where user can extend and integrate to applications using APIs, SDK and Embedded Chat, like how flowise does

**Comment by DahnM20** [comment]
Sorry for the late reply, but I was actually thinking about it.

I've been working on expanding the app, particularly by enabling users to create custom nodes. It's just the beginning, and there might be more changes in the future to keep things clear and organized. You can find more details at [docs.ai-flow.net](https://docs.ai-flow.net/docs/contribute/create-new-node).

As for connecting with other apps, we have a WebSocket API and a REST API. I'll make some adjustments and add clearer explanations in the next few weeks.

Regarding the embedded chat, could you detail your idea? I know Flowise has a chat, but from what I saw, Flowise aims to create an LLM, so it makes sense to interact with it. Ai-Flow is more like a sequence of actions. But tell me and I'll see what I can do.

**Comment by DahnM20** [comment]
Regarding the embedded chat feature, at this moment, it’s unclear how this feature would integrate effectively with the app. If you have additional details, feel free to share them. For now, I will close this issue.
