### ISSUE TITLE
Latest release error

### ISSUE THREAD

**Issue by ArtisticMusician** [DahnM20/ai-flow#6]
When I click to download the latest release I get an Access Denied error

AccessDeniedAccess DeniedK48ZMVP0Q1JG37XBI9PwamqUL6vJPl40yhC22VbXNzkulvkVM85Htc6OmiJLGPHWNiN7L1d1KT5SZv1O1Jnsb93SnQ2ZU5q9dUoSvgC/mlJBTUXo

**Comment by DahnM20** [comment]
Thanks for telling me, it should be good now!
